[package]
name = "mjwarp-rs"
version = "0.1.0"
edition = "2024"

[features]
default = []
cuda-probe = ["dep:cudarc"]
cubecl-cpp-probe = ["cuda-probe", "dep:cubecl-core", "dep:cubecl-cpp"]
cubecl-llvm-probe = ["cuda-probe", "dep:cubecl-core", "dep:cubecl-llvm"]

[dependencies]
cudarc = { version = "=0.18.2", optional = true, default-features = false, features = ["std", "driver", "nvrtc", "dynamic-loading", "cuda-12000"] }
cubecl-core = { git = "https://github.com/tracel-ai/cubecl.git", rev = "1f73b9f63de50a17398c1d5278e2a5f11612c7e1", optional = true, default-features = false, features = ["std", "nvidia"] }
cubecl-cpp = { git = "https://github.com/tracel-ai/cubecl.git", rev = "1f73b9f63de50a17398c1d5278e2a5f11612c7e1", optional = true, default-features = false, features = ["std", "cuda"] }
cubecl-llvm = { git = "https://github.com/tracel-ai/cubecl.git", rev = "1f73b9f63de50a17398c1d5278e2a5f11612c7e1", optional = true, default-features = false, features = ["std", "nvptx"] }
